// await page.goto('https://newpwa.manduu.app/account/register');
// await page.locator('man-input').filter({ hasText: 'First Name *' }).getByRole('textbox').click();
// await page.locator('man-input').filter({ hasText: 'First Name *' }).getByRole('textbox').fill('test');
// await page.locator('man-input').filter({ hasText: 'First Name *' }).getByRole('textbox').press('Tab');
// await page.locator('man-input').filter({ hasText: 'Last Name *' }).getByRole('textbox').fill('manduu');
// await page.locator('input[type="email"]').click();
// await page.locator('input[type="email"]').click();
// await page.locator('input[type="email"]').click();
// await page.locator('input[type="email"]').fill('testmanduu4@gmail.com');
// await page.getByRole('textbox').nth(2).press('Control+a');
// await page.getByRole('textbox').nth(2).press('Control+c');
// await page.getByRole('textbox').nth(3).click();
// await page.getByRole('textbox').nth(3).fill('testmanduu4@gmail.com');
// await page.getByRole('button', { name: 'Continue ' }).click();
// await page.locator('#ScheduledDate').click();
// await page.getByRole('button', { name: '‹' }).click({
//     clickCount: 3
//   });
// await page.locator('input[type="text"]').click();
// await page.locator('input[type="text"]').fill('(054) 322-2222');
// await page.locator('div').filter({ hasText: /^Password$/ }).getByRole('textbox').click();
// await page.locator('div').filter({ hasText: /^Password$/ }).getByRole('textbox').fill('123456');
// await page.locator('div').filter({ hasText: /^Confirm Password$/ }).getByRole('textbox').click();
// await page.locator('div').filter({ hasText: /^Confirm Password$/ }).getByRole('textbox').fill('123456');
// await page.getByRole('button', { name: 'Continue' }).click();
// await page.getByRole('button', { name: 'No, I do not have any of' }).click();
// await page.locator('app-session-appointment div').filter({ hasText: 'Select Studio-- Select Studio' }).getByRole('combobox').selectOption('47');
// await page.locator('#ScheduledDate').click();
// await page.getByRole('button', { name: '›' }).click();
// await page.getByText('16').click();
// await page.getByRole('button', { name: 'Continue ' }).click();
// await page.getByRole('button', { name: 'Next' }).click();
// await page.goto('https://newpwa.manduu.app/app/client/onboarding');
// await page.getByRole('button', { name: 'Complete Profile' }).click();
// await page.getByRole('combobox').first().selectOption('male');
// await page.locator('div').filter({ hasText: /^CountrySelect CountryUnited States of AmericaCanadaMexico$/ }).getByRole('combobox').selectOption('United States');
// await page.getByRole('combobox').nth(2).selectOption('Arkansas');
// await page.getByText('City *').click();
// await page.getByText('State *').click();
// await page.locator('.px-6 > .grid > div:nth-child(2)').first().click();
// await page.locator('man-input').filter({ hasText: 'City *' }).getByRole('textbox').fill('acc');
// await page.locator('man-input').filter({ hasText: 'Zip Code *' }).getByRole('textbox').click();
// await page.locator('man-input').filter({ hasText: 'Zip Code *' }).getByRole('textbox').fill('445555');
// await page.locator('man-input').filter({ hasText: 'Street *' }).getByRole('textbox').click();
// await page.locator('man-input').filter({ hasText: 'Street *' }).getByRole('textbox').fill('cssaasdf');
// await page.getByRole('button', { name: 'Save' }).click();
// await page.getByRole('button', { name: 'Complete Client Info' }).click();
// await page.locator('div').filter({ hasText: /^Heigh\(Feet\)Selected Inch4567$/ }).getByRole('combobox').selectOption('5');
// await page.locator('div').filter({ hasText: /^Heigh\(Inches\)Selected Height01234567891011$/ }).getByRole('combobox').selectOption('7');
// await page.locator('man-input').filter({ hasText: 'Enter Full Name *' }).getByRole('textbox').click();
// await page.locator('man-input').filter({ hasText: 'Enter Full Name *' }).getByRole('textbox').fill('tesr');
// await page.locator('man-input').filter({ hasText: 'Lastname *' }).getByRole('textbox').fill('m');
// await page.locator('man-input').filter({ hasText: 'Lastname *' }).getByRole('textbox').click();
// await page.locator('man-input').filter({ hasText: 'Lastname *' }).getByRole('textbox').fill('mand');
// await page.locator('div').filter({ hasText: /^Phone Number$/ }).getByRole('textbox').click();
// await page.locator('div').filter({ hasText: /^Phone Number$/ }).getByRole('textbox').fill('(054) 433-3333');
// await page.getByRole('button', { name: 'Save' }).click();
// await page.getByRole('button', { name: 'Sign', exact: true }).click();
// await page.locator('input[name="table1q1"]').nth(1).check();
// await page.locator('input[name="table1q2"]').nth(1).check();
// await page.locator('input[name="table1q3"]').nth(1).check();
// await page.locator('input[name="table1q4"]').nth(1).check();
// await page.getByRole('button', { name: 'Sign Here' }).click();
// await page.locator('input[name="table2q1"]').nth(1).check();
// await page.locator('input[name="table2q2"]').nth(1).check();
// await page.locator('input[name="table2q3"]').nth(1).check();
// await page.locator('input[name="table2q4"]').nth(1).check();
// await page.locator('input[name="table2q5"]').nth(1).check();
// await page.locator('input[name="table2q6"]').nth(1).check();
// await page.locator('input[name="table2q7"]').nth(1).check();
// await page.locator('input[name="table2q8"]').nth(1).check();
// await page.getByRole('button', { name: 'Click To Sign' }).first().click();
// await page.locator('input[name="table3q1"]').nth(1).check();
// await page.locator('input[name="table3q2"]').nth(1).check();
// await page.locator('input[name="table3q4"]').nth(1).check();
// await page.getByRole('button', { name: 'Click To Sign' }).nth(1).click();
// await page.locator('div').filter({ hasText: /^Draw SignatureClick To Sign$/ }).getByRole('button').click();
// await page.getByRole('button', { name: ' Sign' }).click();
// await page.getByRole('button', { name: 'First Appointment' }).click();
// await page.getByRole('button', { name: 'Continue' }).click();
// await page.getByRole('button', { name: 'Edit Waiver' }).click();